name: mlflutter
description: "A Flutter app for the Machine Learning Hub."
publish_to: 'none'

version: 0.1.0+6


environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  cross_file:        ^0.3.4   # Work with files across multiple platforms.
  desktop_drop: ^0.6.0   # Drag and drop file functionality.
  # dropdown_search:   ^5.0.6   # Choose the input audio language option.
  dropdown_search: ^6.0.0   # Choose the input audio language option.
  file_picker:       ^10.2.0  # Choose a file from local storage.
  flutter_riverpod:  ^2.5.1   # Keep track of the commands to write on the log page.
  # intl:              ^0.19.0  # Format timestamps.
  markdown_tooltip:  ^0.0.2   # Allow tool tips to be formatted.
  mime: ^2.0.0   # Detect the input file type.
  package_info_plus: ^8.1.1   # Query the version number of the app.
  path:              ^1.9.0   # Cross-platform path manipulation
  window_manager: ^0.5.0   # Fix the size of the desktop app window.
  solidpod:
    git:
      url: https://github.com/anusii/solidpod.git
      ref: dev
  path_provider: ^2.0.11
  open_file: ^3.2.1
  pdf: ^3.11.3
  printing: ^5.14.2
  syncfusion_flutter_pdf: ^30.1.37
  shared_preferences: ^2.0.15

  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint: ^0.7.0
  dependency_validator: ^4.1.1
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.3.5

  # The original `dart-code-metrics` is end of live and has migrated to
  # a paid service. This fork maintains it's compatibility with the
  # latest flutter.

  dart_code_metrics:
    git:
      url: https://github.com/anusii/dart-code-metrics.git
      ref: main

dependency_overrides:
  collection: ^1.19.0 # Required for dart-code-metrics.
  flutter_secure_storage_linux: ^2.0.1
  flutter_secure_storage_platform_interface: ^2.0.0
  intl: ^0.19.0 # Required for solidpod -> form_builder_validators -> flutter_localizations

flutter:
  uses-material-design: true

  assets:
    - assets/images/
